project:
  type: website
  output-dir: docs
  resources:
    - /files
    - /img
    - /data

website:
  title: "Roberto Ascari"
  search: false
  navbar: 
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: paper.qmd
        text: Papers
      - href: teaching.qmd
        text: Teaching
      - href: conference.qmd
        text: Seminars & Conferences
      - href: thesis.qmd
        text: Thesis (ITA)
      

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
editor: visual

