---
title: ""
---

## Academic positions

University of Milano-Bicocca, Department of Economics, Management and Statistics (DEMS), Milan, Italy.

-   [**Assistant Professor (RTD-B)**]{.text-primary}, Mar. 2024 - Present;
-   Assistant Professor (RTD-A), Mar. 2022 - Feb. 2024;
-   Postdoctoral fellow, Jun. 2019 - Feb. 2021;
-   Research associate, Apr. 2019 - Jun. 2019.

## Education

-   [**Ph.D. in Statistics and Mathematics for Finance,**]{.text-primary} University of Milano-Bicocca.\
    **Period:** Nov. 2015 - Oct. 2018.\
    **Thesis:** *A family of flexible mixture distributions for constrained data.*\
    **Advisor:** Prof. Andrea Ongaro.

-   [**M.Sc. in Biostatistics,**]{.text-primary} University of Milano-Bicocca.\
    **Period:** Oct. 2013 - Oct. 2015. Final mark: 110/110 with honors.\
    **Thesis:** *MCMC Bayesian estimation for a particular mixture model on the simplex.*\
    **Advisor:** Prof. Sonia Migliorati.

-   [**B.Sc. in Statistics and Information Management,**]{.text-primary} University of Milano-Bicocca.\
    **Period:** Sept. 2010 - Sept. 2013. Final mark: 107/110.\
    **Thesis:** *Mortality and respiratory tract infections in a population of 7000 patients undergoing cardiac surgery.*\
    **Advisor:** Prof. Vincenzo Bagnardi.

## Award

-   [**Young Talents Award,**]{.text-primary} 2024 Edition - University of Milano-Bicocca with the sponsorship of the "Accademia Nazionale dei Lincei". [Third Prize](https://www.unimib.it/news/premio-giovani-talenti-ecco-vincitori-delledizione-2024)

## Scientific Societies

-  I am member of the Italian Statistical Society ([SIS](https://www.sis-statistica.it/)).
- I was a member of the young section of the Italian Statistical Society ([ySIS](https://youngsis.github.io/)).
- I was a member of the International Society for Bayesian Analysis ([ISBA](https://bayesian.org/)) and its junior sections. 
- I was a member of the "Gruppo Nazionale per l’Analisi Matematica, la Probabilità e le loro Applicazioni" ([GNAMPA](https://www.altamatematica.it/gnampa/)).