---
title: ""
editor: visual
---

## Published papers

- Accepted - **Ascari, R.**, Migliorati, S., Ongaro, A. A new Dirichlet-multinomial mixture regression model for the analysis of microbiome data. [***Statistics in Medicine***]{.text-primary}, [10.1002/sim.70220]{https://doi.org/10.1002/sim.70220).


-   2025 - Giampino, A., **Ascari, R.**, Migliorati, S. A flexible mixed-membership model for community and enterotype detection for microbiome data. [***Computational Statistics and Data Analysis***]{.text-primary}, [10.1016/j.csda.2025.108181](https://doi.org/10.1016/j.csda.2025.108181).

-   2025 - Conforti, F., Nekljudova, V., Sala, I., **Ascari, R.**, **et al.** Surrogate end points for overall survival in neoadjuvant randomized clinical trials for early breast cancer, [***Journal of Clinical Oncology***]{.text-primary}, [10.1200/JCO-24-01360](https://doi.org/10.1200/JCO-24-01360).

-   2024 - Colicino, E., **Ascari, R.**, Saddiki, H., **et al.** Cross-cohort mixture analysis: a data integration approach with applications on gestational age and DNA-methylation-derived gestational age acceleration metrics. [***Biometrical Journal***]{.text-primary}, 66(8), [10.1002/bimj.202300270](https://dx.doi.org/10.1002/bimj.202300270).

-   2024 - Gerli, S., **Ascari, R.**, Migliorati, S., Cigna, T., Borrotti, M. Beyond human labelling: an automatic topic identification framework for big web data. [***Electronic Journal of Applied Statistical Analysis***]{.text-primary}, 17(03), 545--571, [10.1285/i20705948v17n3p545](https://dx.doi.org/10.1285/i20705948v17n3p545).

-   2024 - Ongaro, A., Migliorati, S., **Ascari, R.**, Ripamonti, E. Testing practical relevance of treatment effects. [***Statistical Papers***]{.text-primary}, 65, 4121--4145, [10.1007/s00362-024-01549-x](https://dx.doi.org/10.1007/s00362-024-01549-x).

-   2024 - **Ascari, R.**, Giabelli, A., Malandri, L., Mercorio, F., Mezzanzanica, M. A Fistful of Vectors: A Tool for Intrinsic Evaluation of Word Embeddings. [***Cognitive Computation***]{.text-primary}, 16, 949--963, [10.1007/s12559-023-10235-3](https://dx.doi.org/10.1007/s12559-023-10235-3).

-   2024 - **Ascari, R.**, Di Brisco, A.M., Migliorati, S., Ongaro, A. A Multivariate Mixture Regression Model for Constrained Responses. [***Bayesian Analysis***]{.text-primary}, 19(2), 377--405, [10.1214/22-BA1359](https://dx.doi.org/10.1214/22-BA1359).

-   2021 - **Ascari, R.**, Migliorati, S. A new regression model for overdispersed binomial data accounting for outliers and an excess of zeros. [***Statistics in Medicine***]{.text-primary}, 40(17), 3895--3914, [10.1002/sim.9005](https://doi.org/10.1002/sim.9005).

-   2021 - Oliveira dos Anjos, T.B., \[et al., including **Ascari, R.**\]. Eutrophic status influences the impact of pesticide mixtures and predation on Daphnia pulex populations. [***Ecology and Evolution***]{.text-primary}, 11(9), 4046--4057, [10.1002/ece3.7305](https://doi.org/10.1002/ece3.7305).

-   2021 - Sorrentino, S., **Ascari, R.**, et al. (2021). Microglial heterogeneity and its potential role in driving phenotypic diversity of alzheimer’s disease. [***International Journal of Molecular Sciences***]{.text-primary}, 22(5), 2780, [10.3390/ijms22052780](https://doi.org/10.3390/ijms22052780).

-   2021 - Maranzano, P., **Ascari, R.**, Chiodini, P.M., Manzi, G. Analysis of sustainability of bike-sharing customers using Partially Ordered Sets methodology. [***Social Indicator Research***]{.text-primary}, 157, 123--138, [10.1007/s11205-020-02333-8](https://doi.org/10.1007/s11205-020-02333-8).

-   2020 - Ongaro, A., Migliorati, S., **Ascari, R.** A new mixture model on the simplex. [***Statistics and Computing***]{.text-primary}, 30, 749-770, [10.1007/s11222-019-09920-x](https://doi.org/10.1007/s11222-019-09920-x).

-   2015 - Scandroglio, A., Finco, G., \[et al, including **Ascari, R.**\]. Cardiac surgery in 260 octogenarians: a case series. [***BMC Anesthesiology***]{.text-primary}, 15. [10.1186/1471-2253-15-15](https://doi.org/10.1186/1471-2253-15-15).

-   2015 - Pieri, M., Landoni, G., \[et al, including **Ascari, R.**\]. Methicillin-resistant staphylococcus species in a cardiac surgical intensive care unit. [***Signa Vitae***]{.text-primary}, 10(2), 65--68, [10.22514/SV102.122015.5](https://doi.org/10.22514/SV102.122015.5).

## Submitted papers

-   FlexReg: an R package for fitting regression models on bounded univariate responses. To be resubmitted. Joint work with Agnese M. Di Brisco, Sonia Migliorati, and Andrea Ongaro.

## Contribution as book chapter

-  2025 - Montagna, S. **Ascari, R.**, Khorrami Chokami, A. Spectral Synchronicity of EMG Signals: An Application to the Erector Spinae Muscles of Sitting Violinists. [10.1007/978-3-031-96033-8_9](https://doi.org/10.1007/978-3-031-96033-8_9).

-  2025 - Di Brisco, A.M., **Ascari, R.**, Fiori, A.M., Nicolussi, F. Exploring Dependencies in Compositional Data with Graphical Models. [10.1007/978-3-031-95995-0_22](https://doi.org/10.1007/978-3-031-95995-0_22).

- 2025 - Giampino, A., **Ascari, R.**, Migliorati, S. Microbiome Enterotype Detection via a Latent Variable Allocation Model. [10.1007/978-3-031-64447-4_16](https://doi.org/10.1007/978-3-031-64447-4_16).

-  2025 - **Ascari, R.**, Di Brisco, A.M., Migliorati, S. A New Distribution for Overdispersed Count Data. [10.1007/978-3-031-64431-3_14](https://doi.org/10.1007/978-3-031-64431-3_14).

-  2024 - Giampino, A., **Ascari, R.**, Migliorati, S. A Flexible Generalization of the Latent Dirichlet Allocation. [10.1002/9781394316915.ch8](https://doi.org/10.1002/9781394316915.ch8).

-  2023 - **Ascari, R.**, Migliorati, S. A New Regression Model for the Analysis of Microbiome Data. [10.1007/978-3-031-09034-9_5](https://doi.org/10.1007/978-3-031-09034-9_5).

-  2022 -  **Ascari, R.**, Migliorati, S. A new regression model for count compositions. [10.1002/9781394165544.ch2](https://doi.org/10.1002/9781394165544.ch2).

- 2022 - Di Brisco, A.M., **Ascari, R.**, Migliorati, S., Ongaro, A. The State of the Art in Flexible Regression Models for Univariate Bounded Responses. [10.1002/9781394165513.ch8](https://doi.org/10.1002/9781394165513.ch8).

-   2022 - Di Brisco, A.M., **Ascari, R.**, Migliorati, S., Ongaro, A. Simulation Studies for a Special Mixture Regression Model with Multivariate Responses on the Simplex. [10.1002/9781394165513.ch9](https://doi.org/10.1002/9781394165513.ch9).

-   2021 - **Ascari, R.**, Migliorati, S. A full mixture of experts model to classify constrained data. [10.36253/978-88-5518-340-6](https://doi.org/10.36253/978-88-5518-340-6).

-   2021 - **Ascari, R.**, Migliorati, S., Ongaro, A. The Double Flexible Dirichlet: A Structured Mixture Model for Compositional Data. [10.1002/9781119821724.ch10](https://doi.org/10.1002/9781119821724.ch10).

-   2019 - **Ascari, R.**, Migliorati, S., Ongaro, A. Bayesian inference for a mixture model on the simplex. [10.1007/978-3-030-21140-0_11](https://doi.org/10.1007/978-3-030-21140-0_11).