---
title: "Tesi"
format: html
editor: visual
---

## Laureandə

Di seguito viene riportato il numero di disponibilità di tesi per le future sessioni di laurea. Tendenzialmente, non vengono accettatə più di **quattro** tesistə per appello di laurea.

| Appello di laurea | Posti liberi |
|-------------------|--------------|
| Marzo 2027        | 0            |
| Luglio 2027       | 2            |
| Ottobre 2027      | 4            |
| Dicembre 2027     | 4            |


**N.B.:** A partire dalla sessione di laurea di luglio 2027 (inclusa), ogni tesista dovrà presentare il proprio lavoro di tesi mediante una presentazione in presenza del relatore. Questo si applica esclusivamente alle tesi seguite dal sottoscritto in qualità di relatore.

## Possibili Argomenti Tesi

-   L'extended flexible Dirichlet: un modello mistura per dati composizionali.

-   Modelli di regressione per proporzioni (i.e., risposte definite su $(0,1)$).

-   Modelli di regressione per dati binomiali sovradispersi.

-   Clustering per dati qualitativi e quantitativi: l'algoritmo dei $k$ prototipi.

-   L'algoritmo dei $k$ prototipi per il clustering di dati composizionali con zeri.

-   Latent topic models per l'analisi dei gruppi di ricerca della sezione di Statistica del DEMS.

<!-- -   Regressioni penalizzate: Ridge e Lasso. -->

<!-- -   Latent topic models per dati del microbioma umano. -->

<!-- -   La regressione di Cox per l'analisi della sopravvivenza. -->

<!-- -   Distribuzione binomiale negativa e relativo modello di regressione. -->

<!-- -   Il modello di regressione lineare con approccio Bayesiano. -->

<!-- -   Il metodo bootstrap ed i modelli di regressione. -->

## Informazioni Scrittura Tesi

Si consiglia caldamente l'utilizzo di [**LaTeX**]{.text-primary} per la scrittura della propria tesi. In particolare, [**Overleaf**](https://www.overleaf.com) è una piattaforma online che facilita la scrittura e la collaborazione su documenti in LaTeX. Offre un editor intuitivo accessibile da qualsiasi dispositivo, senza necessità di dover installazione software. Tra le sue funzionalità principali:

-   [Collaborazione]{.text-primary} in tempo reale: più utenti possono lavorare simultaneamente sullo stesso documento, visualizzando immediatamente le modifiche degli altri.

-   Controllo delle versioni: mantiene traccia delle modifiche, permettendo di ripristinare versioni precedenti del documento.

-   Ampia gamma di [template]{.text-primary}: dispone di migliaia di modelli predefiniti per articoli scientifici, tesi, presentazioni e altro, facilitando l'avvio di nuovi progetti.

-   Compilazione automatica: genera istantaneamente l'anteprima del documento, evidenziando eventuali errori di compilazione.

-   Gestione integrata della [bibliografia]{.text-primary}: supporta l'inserimento e la formattazione automatica delle citazioni bibliografiche.

Questo [template](files/Template_Tesi.zip) può essere scaricato e modificato per iniziare a scrivere la propria tesi. Su Overleaf si clicchi su "Nuovo Progetto" e scegliere "Carica Progetto". Una volta compilato il progetto, il risultato dovrebbe [questo](files/Template_Tesi.pdf). Un ringraziamento a Tommaso Rigon per la base del template.
